### PR TITLE
fix: pass a reference to CopyCodeButton to prevent re-render

### LINKED ISSUE #70: fix: while responses are being generated, copy code buttons become difficult to click
**Platform**
OSX Chrome

**Description**
While a response is being streamed in, if there is a codeblock with a copy code button, clicking on it will seem to do nothing or require many clicks.

I believe this is because the button is being re-rendered on every new token? Regardless, should always be easy to click the button whether text is generating or not.

### PR DESCRIPTION
**Pull request by DJRHails**
## Motivation

Fixes #70 

## Solution

- Use RefObject to store the children for the copy-paste button to prevent re-rendering.
- Move components and rehypePlugins to outer scope to prevent re-creation on render (useMemo could also be used, but I think this is cleaner).

## Checklist

- [x] Tested in Chrome
- [x] Tested in Safari

### CODE REVIEW

**Comment by DJRHails** [comment]
@transmissions11 anything I can do to help get this merged in?

File: src/components/utils/Markdown.tsx [hunk 1]
```diff
@@ -66,84 +67,101 @@ const CopyCodeButton = ({ code }: { code: ReactNode[] }) => {
...
     </Button>
   );
-};
+});
+
+const Codeblock = memo(function Codeblock({ className, inline, children, ...props }: {
+  className?: string;
+  inline?: boolean;
+  children: ReactNode[];
+}) {
```
Comment (transmissions11) [inline src/components/utils/Markdown.tsx:76]: idt memoizing here helps because it wont do a deep compare on children? correct me if im wrong

Comment (DJRHails) [reply src/components/utils/Markdown.tsx:76]: It's true.
> [From PR] Use memo for the remaining components in the file; not entirely necessary, but the performance impact of memo is negligible and prevents annoying to debug re-render issues.

Happy to strip them if you've got a preference to remove them.

Comment (transmissions11) [reply src/components/utils/Markdown.tsx:76]: > [E.g. the coinbase way](https://attardi.org/why-we-memo-all-the-things/)

oo this post and perspective is interesting — though [kentcdodds seems to disagree](https://twitter.com/kentcdodds/status/1452716184869109760?s=20) (however my guess is he just read the title as this post doesnt rly address these points head on lol)

i think we should keep the diff as minimal as possible for this PR and just not memo these functions — but would be open to discussing in an issue whether we should adopt the coinbase way going forward

Comment (DJRHails) [reply src/components/utils/Markdown.tsx:76]: Appreciate the follow up post - tend to agree it doesn't address the points. I think it's a React idiosyncrasy that makes the performance overhead minimal (kentcdodds says so himself a few times "incidentally [the performance hit] is probably happening anyway") and is definitely not good advice generally.

Anyway for the purpose of this PR: I'll strip them out tonight 😄

Comment (DJRHails) [reply src/components/utils/Markdown.tsx]: Done!

**Comment by transmissions11** [comment]
lgtm! nice work
